"use client";

import { useEffect, useState } from "react";
import type { GovernanceEffect, GovernanceProposal, GovernanceStage, Tension } from "@/lib/domain";
import type { WorkspaceData } from "@/lib/supabase/workspace";
import { HelpTip } from "@/components/guidance";
import { GovernanceEffectEditor, governanceEffectIsComplete, governanceEffectSummary } from "@/components/governance-effect-editor";

export function WorkspaceGovernanceMeeting({ proposal, tension, workspace, personName, onChange, onAccept, onClose }: { proposal: GovernanceProposal; tension?: Tension; workspace: WorkspaceData; personName: (id: string) => string; onChange: (proposal: GovernanceProposal) => Promise<void>; onAccept: (proposal: GovernanceProposal) => Promise<void>; onClose: () => void }) {
  const [note, setNote] = useState(proposal.meetingNotes[proposal.stage] ?? "");
  const [proposalText, setProposalText] = useState(proposal.proposal);
  const [effect, setEffect] = useState<GovernanceEffect | undefined>(proposal.governanceEffect);
  useEffect(() => { setNote(proposal.meetingNotes[proposal.stage] ?? ""); setProposalText(proposal.proposal); setEffect(proposal.governanceEffect); }, [proposal]);
  const steps: GovernanceStage[] = ["present_proposal", "clarifying_questions", "reaction_round", "clarify", "objection_round", "integration"];
  const index = steps.indexOf(proposal.stage);
  async function move(stage: GovernanceStage, text = proposalText) { await onChange({ ...proposal, proposal: text.trim() || proposal.proposal, governanceEffect: effect, stage, meetingNotes: { ...proposal.meetingNotes, [proposal.stage]: note.trim() } }); }
  const currentProposal = { ...proposal, proposal: proposalText.trim() || proposal.proposal, governanceEffect: effect, meetingNotes: { ...proposal.meetingNotes, [proposal.stage]: note.trim() } };
  return <div className="governance-meeting-surface"><div className="meeting-window-head"><div><span className="section-kicker">Governance meeting</span><h1>{proposal.title}</h1><p>{tension?.title ?? "Structural proposal"}</p></div><button className="quiet" onClick={onClose}>Close meeting</button></div><article className="governance-proposal-card"><div className="governance-proposal-head"><div><span className="kind">Proposed by {personName(proposal.proposerId)}</span><h3>{stageName(proposal.stage)}</h3></div><span className="governance-stage-badge">{Math.max(index + 1, 1)} / 6</span></div><div className="governance-proposal-text"><strong>Current proposal</strong><p>{proposal.proposal}</p></div><div className="effect-summary-line meeting-effect-summary"><strong>Resulting governance</strong><span>{governanceEffectSummary(effect, workspace.roles, workspace.standingAgreements)}</span></div><div className="governance-round"><GovernanceStepGuide stage={proposal.stage} />
    {proposal.stage === "present_proposal" && <MeetingNav onNext={() => void move("clarifying_questions")} next="Start clarifying questions" />}
    {proposal.stage === "clarifying_questions" && <><MeetingNote value={note} setValue={setNote} label="Useful clarification (optional)" /><MeetingNav onPrevious={() => void move("present_proposal")} onNext={() => void move("reaction_round")} next="Start reaction round" /></>}
    {proposal.stage === "reaction_round" && <><MeetingNote value={note} setValue={setNote} label="Useful reactions to retain (optional)" /><MeetingNav onPrevious={() => void move("clarifying_questions")} onNext={() => void move("clarify")} next="Give proposer option to clarify" /></>}
    {proposal.stage === "clarify" && <><label className="field"><span>Proposal</span><textarea rows={5} value={proposalText} onChange={(event) => setProposalText(event.target.value)} /></label><GovernanceEffectEditor effect={effect} roles={workspace.roles} standingAgreements={workspace.standingAgreements} onChange={setEffect} /><MeetingNav onPrevious={() => void move("reaction_round")} onNext={() => void move("objection_round", proposalText)} next="Open objection round" /></>}
    {proposal.stage === "objection_round" && <><div className="objection-essential"><strong>An objection is not a preference, disagreement, or a better idea.</strong><p>It identifies a concrete way this proposal could harm SDBP or move it backward.</p><HelpTip label="How do we test an objection?"><strong>Test the reasoning, not the person.</strong><br />Ask whether the harm is caused or worsened by adopting this proposal, whether it matters to SDBP or a role the objector represents, and whether there would be too little time to adapt before significant harm occurs.</HelpTip></div><ol className="objection-tests"><li><span>1</span><p>What concrete harm or loss of capacity would this proposal create?</p></li><li><span>2</span><p>Is that problem caused or made worse by adopting this proposal?</p></li><li><span>3</span><p>Is it significant enough that the proposal should not proceed as written?</p></li></ol><MeetingNote value={note} setValue={setNote} label="Objection to integrate (optional)" /><div className="process-actions"><button className="quiet" onClick={() => void move("clarify")}>Previous</button><button className="secondary" onClick={() => void move("integration")}>Objection needs integration</button><button className="primary" disabled={!governanceEffectIsComplete(effect)} onClick={() => void onAccept(currentProposal)}>No objections · accept</button></div></>}
    {proposal.stage === "integration" && <><label className="field"><span>Integrated proposal</span><textarea rows={5} value={proposalText} onChange={(event) => setProposalText(event.target.value)} /></label><GovernanceEffectEditor effect={effect} roles={workspace.roles} standingAgreements={workspace.standingAgreements} onChange={setEffect} /><MeetingNote value={note} setValue={setNote} label="What was integrated?" /><MeetingNav onPrevious={() => void move("objection_round")} onNext={() => void move("objection_round", proposalText)} next="Return to objection round" /></>}
  </div></article></div>;
}
function GovernanceStepGuide({ stage }: { stage: GovernanceStage }) { const guide = governanceGuide(stage); return <div className="meeting-step-guide"><span className="kind">What is happening now</span><h4>{guide.heading}</h4><p>{guide.body}</p><div className="facilitator-cue"><strong>Facilitator</strong><span>{guide.facilitator}</span></div></div>; }
function MeetingNote({ value, setValue, label }: { value: string; setValue: (value: string) => void; label: string }) { return <label className="field"><span>{label}</span><textarea rows={3} value={value} onChange={(event) => setValue(event.target.value)} /></label>; }
function MeetingNav({ onPrevious, onNext, next }: { onPrevious?: () => void; onNext: () => void; next: string }) { return <div className="process-actions">{onPrevious && <button className="quiet" onClick={onPrevious}>Previous</button>}<button className="primary" onClick={onNext}>{next}</button></div>; }
function stageName(stage: GovernanceStage) { return ({ prepared: "Prepared", present_proposal: "Present proposal", clarifying_questions: "Clarifying questions", reaction_round: "Reaction round", clarify: "Option to clarify", objection_round: "Objection round", integration: "Integration", accepted: "Accepted" } as Record<GovernanceStage, string>)[stage]; }
function governanceGuide(stage: GovernanceStage) { return ({ prepared: { heading: "Prepare the proposal before processing it.", body: "A governance proposal changes something that should remain true after today.", facilitator: "Check that it addresses a real structural tension." }, present_proposal: { heading: "Start with the tension, then the proposal.", body: "The proposer explains the gap and presents the proposal. Everyone else listens for understanding.", facilitator: "Make sure the group understands it; do not open discussion yet." }, clarifying_questions: { heading: "Questions only. Reactions wait.", body: "Ask only for information needed to understand the tension or proposal.", facilitator: "If a question contains a reaction, save it for the next round." }, reaction_round: { heading: "Let the proposer hear the room without debate.", body: "Each person may react; these are inputs for the proposer, not instructions.", facilitator: "One reaction at a time, no replies between participants." }, clarify: { heading: "The proposer still owns the proposal.", body: "The proposer may clarify, amend or leave the proposal unchanged. Keep the resulting governance aligned with the wording.", facilitator: "Ask what, if anything, the proposer wants to change." }, objection_round: { heading: "Test whether adopting the proposal would cause real harm.", body: "An objection must identify a concrete problem caused or materially worsened by the proposal.", facilitator: "Test objections one at a time against the visible criteria." }, integration: { heading: "Resolve the objection without losing the reason for the proposal.", body: "Adjust enough to remove valid harm while still addressing the original tension.", facilitator: "Keep the conversation focused on proposer and objector." }, accepted: { heading: "The proposal is now part of SDBP governance.", body: "The explicit governance effect has become current organisational truth.", facilitator: "Confirm the final wording before closing." } } as Record<GovernanceStage, { heading: string; body: string; facilitator: string }>)[stage]; }
