"use client";

import { useState } from "react";
import { people } from "@/lib/mock-data";
import type { GovernanceObjection, GovernanceProposal, GovernanceStage, Tension } from "@/lib/domain";
import { GOVERNANCE_STEPS, OBJECTION_TESTS } from "@/lib/governance-method";
import { humanGovernanceStage, personName } from "@/lib/prototype-utils";

type MarkField = "clarificationDoneIds" | "reactionPassIds" | "objectionPassIds";
type Props = {
  tensions:Tension[]; proposals:GovernanceProposal[]; currentUserId:string; facilitatorId?:string; onGoToTensions:()=>void;
  onCreateProposal:(tensionId:string,title:string,text:string)=>void; onSetStage:(id:string,stage:GovernanceStage)=>void;
  onMarkParticipant:(id:string,field:MarkField,personId:string)=>void; onAddQuestion:(id:string,text:string)=>void;
  onAnswerQuestion:(id:string,qid:string,answer:string)=>void; onAddReaction:(id:string,text:string)=>void;
  onAmendProposal:(id:string,text:string)=>void; onAddObjection:(id:string,concern:string,criteria:[boolean,boolean,boolean,boolean])=>void;
  onReviewObjection:(id:string,oid:string,valid:boolean,note:string)=>void; onBeginIntegration:(id:string)=>void;
  onIntegrate:(id:string,text:string,note:string)=>void; onAccept:(id:string)=>void;
};

export function GovernanceView(props:Props){
  const used=new Set(props.proposals.map(p=>p.tensionId));
  const ready=props.tensions.filter(t=>t.status==="governance"&&!used.has(t.id));
  const active=props.proposals.filter(p=>p.stage!=="accepted");
  const accepted=props.proposals.filter(p=>p.stage==="accepted");
  return <div className="governance-layout"><section className="governance-stage">
    <span className="section-kicker">Start here</span><h2>A governance process starts from a structural tension</h2>
    <p>Process a tension and choose <strong>Governance</strong> when resolving it requires changing an ongoing role, accountability, domain or policy. The raiser then turns that tension into a concrete proposal here.</p>
    {ready.length?<div className="governance-ready-list">{ready.map(t=><Starter key={t.id} tension={t} user={props.currentUserId} create={props.onCreateProposal}/>)}</div>:!active.length&&<div className="calm-empty compact-empty"><span>○</span><h3>No structural tension is waiting for a proposal</h3><p>To test Governance, raise a tension, process it, and choose Governance.</p><button className="secondary small" onClick={props.onGoToTensions}>Go to Tensions</button></div>}
    {!!active.length&&<section className="section"><div className="section-head"><div><span className="section-kicker">In process</span><h2>Governance proposals</h2></div></div><div className="governance-proposal-stack">{active.map(p=><ProposalCard key={p.id} proposal={p} {...props}/>)}</div></section>}
    {!!accepted.length&&<section className="section"><div className="section-head"><div><span className="section-kicker">Decided</span><h2>Accepted governance</h2></div></div><div className="soft-list">{accepted.map(p=><div className="soft-row" key={p.id}><div><strong>{p.title}</strong><small>{p.proposal}</small></div><span className="definition-status defined">accepted</span></div>)}</div></section>}
    <MethodGuide facilitatorId={props.facilitatorId}/>
  </section><aside className="governance-note"><span className="kind">Test the handoffs</span><h3>Switch people during the rounds</h3><p>Use <strong>Test as</strong> in the sidebar. The proposer, other board members and Process Steward each have different actions.</p><div className="note-divider"/><h3>Governance</h3><p>Changes an ongoing role, accountability, domain or policy. One-off work stays in Work or Tensions.</p></aside></div>;
}

function Starter({tension,user,create}:{tension:Tension;user:string;create:(id:string,title:string,text:string)=>void}){
  const [open,setOpen]=useState(false),[title,setTitle]=useState(""),[text,setText]=useState("");
  const mine=tension.raiserId===user;
  return <article className="governance-starter"><span className="kind">Structural tension · {personName(tension.raiserId)}</span><h3>{tension.title}</h3><p>{tension.latestNote}</p>{!mine?<small>Waiting for {personName(tension.raiserId)} to present a proposal.</small>:!open?<button className="primary small" onClick={()=>setOpen(true)}>Create proposal</button>:<div className="governance-inline-form"><label className="field"><span>Proposal title</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field"><span>Proposed governance change</span><textarea rows={4} value={text} onChange={e=>setText(e.target.value)}/></label><div className="process-actions"><button className="quiet" onClick={()=>setOpen(false)}>Cancel</button><button className="primary small" disabled={!title.trim()||!text.trim()} onClick={()=>create(tension.id,title,text)}>Present proposal</button></div></div>}</article>;
}

function ProposalCard({proposal,currentUserId,facilitatorId,onSetStage,onMarkParticipant,onAddQuestion,onAnswerQuestion,onAddReaction,onAmendProposal,onAddObjection,onReviewObjection,onBeginIntegration,onIntegrate,onAccept}:Props&{proposal:GovernanceProposal}){
  const proposer=proposal.proposerId===currentUserId;
  const participants=people.filter(p=>p.id!==proposal.proposerId).map(p=>p.id);
  const step=GOVERNANCE_STEPS.findIndex(s=>s.id===proposal.stage);
  const clarificationDone=participants.every(id=>proposal.clarificationDoneIds.includes(id))&&proposal.questions.every(q=>!!q.answer);
  const reactionsDone=participants.every(id=>proposal.reactionPassIds.includes(id)||proposal.reactions.some(r=>r.authorId===id));
  const objectionsDone=participants.every(id=>proposal.objectionPassIds.includes(id)||proposal.objections.some(o=>o.authorId===id));
  const candidate=proposal.objections.filter(o=>o.status==="candidate"), valid=proposal.objections.filter(o=>o.status==="valid");
  return <article className="governance-proposal-card"><div className="governance-proposal-head"><div><span className="kind">Proposed by {personName(proposal.proposerId)}</span><h3>{proposal.title}</h3></div><span className="governance-stage-badge">{humanGovernanceStage(proposal.stage)}</span></div><div className="governance-proposal-text"><strong>Current proposal</strong><p>{proposal.proposal}</p></div>
    <div className="governance-progress">{GOVERNANCE_STEPS.map((s,i)=><span key={s.id} className={i<step?"done":i===step?"active":""}>{i+1}<small>{s.name}</small></span>)}</div>
    {proposal.stage==="clarifying_questions"&&<Questions p={proposal} user={currentUserId} proposer={proposer} participants={participants} done={clarificationDone} add={onAddQuestion} answer={onAnswerQuestion} pass={id=>onMarkParticipant(proposal.id,"clarificationDoneIds",id)} next={()=>onSetStage(proposal.id,"reaction_round")}/>} 
    {proposal.stage==="reaction_round"&&<Reactions p={proposal} user={currentUserId} proposer={proposer} participants={participants} done={reactionsDone} add={onAddReaction} pass={id=>onMarkParticipant(proposal.id,"reactionPassIds",id)} next={()=>onSetStage(proposal.id,"clarify")}/>} 
    {proposal.stage==="clarify"&&<Clarify p={proposal} proposer={proposer} amend={onAmendProposal}/>} 
    {proposal.stage==="objection_round"&&<Objections p={proposal} user={currentUserId} proposer={proposer} facilitatorId={facilitatorId} participants={participants} done={objectionsDone} candidate={candidate} valid={valid} add={onAddObjection} pass={id=>onMarkParticipant(proposal.id,"objectionPassIds",id)} review={onReviewObjection} integrate={()=>onBeginIntegration(proposal.id)} accept={()=>onAccept(proposal.id)}/>} 
    {proposal.stage==="integration"&&<Integration p={proposal} proposer={proposer} integrate={onIntegrate}/>} 
  </article>;
}

function Questions({p,user,proposer,participants,done,add,answer,pass,next}:{p:GovernanceProposal;user:string;proposer:boolean;participants:string[];done:boolean;add:(id:string,text:string)=>void;answer:(id:string,qid:string,text:string)=>void;pass:(id:string)=>void;next:()=>void}){
  const [text,setText]=useState(""); const mine=p.questions.some(q=>q.authorId===user), passed=p.clarificationDoneIds.includes(user);
  return <div className="governance-round"><span className="section-kicker">1 · Clarifying Questions</span><h4>Understand the proposal before reacting</h4>{!!p.questions.length&&<div className="governance-entry-list">{p.questions.map(q=><Question key={q.id} q={q} proposer={proposer} answer={a=>answer(p.id,q.id,a)}/>)}</div>}{!proposer&&!mine&&!passed&&<div className="governance-inline-form"><label className="field"><span>Factual question</span><input value={text} onChange={e=>setText(e.target.value)}/></label><div className="process-actions"><button className="secondary small" onClick={()=>pass(user)}>No more questions</button><button className="primary small" disabled={!text.trim()} onClick={()=>{add(p.id,text);setText("");pass(user)}}>Ask question</button></div></div>}<Participation ids={participants} complete={id=>p.clarificationDoneIds.includes(id)}/>{proposer&&<button className="primary small" disabled={!done} onClick={next}>Start Reaction Round</button>}</div>;
}
function Question({q,proposer,answer}:{q:GovernanceProposal["questions"][number];proposer:boolean;answer:(a:string)=>void}){const [text,setText]=useState("");return <div className="governance-entry"><strong>{personName(q.authorId)}</strong><p>{q.text}</p>{q.answer?<small>Answer: {q.answer}</small>:proposer?<div className="governance-review"><input value={text} onChange={e=>setText(e.target.value)}/><button className="primary small" disabled={!text.trim()} onClick={()=>answer(text)}>Answer</button></div>:<small>Waiting for proposer.</small>}</div>}

function Reactions({p,user,proposer,participants,done,add,pass,next}:{p:GovernanceProposal;user:string;proposer:boolean;participants:string[];done:boolean;add:(id:string,text:string)=>void;pass:(id:string)=>void;next:()=>void}){const [text,setText]=useState("");const mine=p.reactions.some(r=>r.authorId===user),passed=p.reactionPassIds.includes(user);return <div className="governance-round"><span className="section-kicker">2 · Reaction Round</span><h4>React without debating</h4>{!!p.reactions.length&&<div className="governance-entry-list">{p.reactions.map(r=><div className="governance-entry" key={r.id}><strong>{personName(r.authorId)}</strong><p>{r.text}</p></div>)}</div>}{!proposer&&!mine&&!passed&&<div className="governance-inline-form"><textarea rows={3} value={text} onChange={e=>setText(e.target.value)}/><div className="process-actions"><button className="secondary small" onClick={()=>pass(user)}>Pass</button><button className="primary small" disabled={!text.trim()} onClick={()=>{add(p.id,text);setText("")}}>Record reaction</button></div></div>}<Participation ids={participants} complete={id=>p.reactionPassIds.includes(id)||p.reactions.some(r=>r.authorId===id)}/>{proposer&&<button className="primary small" disabled={!done} onClick={next}>Continue to Option to Clarify</button>}</div>}
function Clarify({p,proposer,amend}:{p:GovernanceProposal;proposer:boolean;amend:(id:string,text:string)=>void}){const [text,setText]=useState(p.proposal);return <div className="governance-round"><span className="section-kicker">3 · Option to Clarify</span><h4>The proposer may amend after hearing reactions</h4>{proposer?<div className="governance-inline-form"><textarea rows={5} value={text} onChange={e=>setText(e.target.value)}/><button className="primary small" disabled={!text.trim()} onClick={()=>amend(p.id,text)}>Open Objection Round</button></div>:<p>Waiting for {personName(p.proposerId)}.</p>}</div>}

function Objections({p,user,proposer,facilitatorId,participants,done,candidate,valid,add,pass,review,integrate,accept}:{p:GovernanceProposal;user:string;proposer:boolean;facilitatorId?:string;participants:string[];done:boolean;candidate:GovernanceObjection[];valid:GovernanceObjection[];add:(id:string,text:string,c:[boolean,boolean,boolean,boolean])=>void;pass:(id:string)=>void;review:(id:string,oid:string,valid:boolean,note:string)=>void;integrate:()=>void;accept:()=>void}){
  const [text,setText]=useState(""),[checks,setChecks]=useState<[boolean,boolean,boolean,boolean]>([false,false,false,false]); const mine=p.objections.some(o=>o.authorId===user),passed=p.objectionPassIds.includes(user);
  return <div className="governance-round"><span className="section-kicker">4 · Objection Round</span><h4>Test for harm, not preference</h4><p>Every board member records either no objection or a concern they believe meets all four tests. The facilitator then tests the reasoning.</p>{!proposer&&!mine&&!passed&&<div className="governance-inline-form"><textarea rows={3} value={text} onChange={e=>setText(e.target.value)} placeholder="Concern…"/><div className="objection-checklist">{OBJECTION_TESTS.map((t,i)=><label key={t}><input type="checkbox" checked={checks[i]} onChange={e=>setChecks(c=>c.map((v,j)=>j===i?e.target.checked:v) as [boolean,boolean,boolean,boolean])}/><span><strong>Test {i+1}</strong>{t}</span></label>)}</div><div className="process-actions"><button className="secondary small" onClick={()=>pass(user)}>No objection</button><button className="primary small" disabled={!text.trim()||!checks.every(Boolean)} onClick={()=>{add(p.id,text,checks);setText("");setChecks([false,false,false,false])}}>Submit concern</button></div></div>}{!!p.objections.length&&<div className="governance-entry-list">{p.objections.map(o=><ObjectionCard key={o.id} p={p.id} o={o} user={user} facilitatorId={facilitatorId} review={review}/>)}</div>}<Participation ids={participants} complete={id=>p.objectionPassIds.includes(id)||p.objections.some(o=>o.authorId===id)}/>{proposer&&done&&!candidate.length&&!valid.length&&<button className="primary small" onClick={accept}>Accept proposal</button>}{proposer&&valid.length>0&&!candidate.length&&<button className="primary small" onClick={integrate}>Integrate objection</button>}{candidate.length>0&&<p className="round-waiting">Waiting for {facilitatorId?personName(facilitatorId):"a facilitator"} to test {candidate.length} concern{candidate.length===1?"":"s"}.</p>}</div>
}
function ObjectionCard({p,o,user,facilitatorId,review}:{p:string;o:GovernanceObjection;user:string;facilitatorId?:string;review:(id:string,oid:string,valid:boolean,note:string)=>void}){const [note,setNote]=useState("");const fac=user===facilitatorId;return <div className={`governance-entry objection-entry objection-${o.status}`}><div className="objection-entry-head"><strong>{personName(o.authorId)}</strong><span>{o.status}</span></div><p>{o.concern}</p>{o.status==="candidate"&&fac?<div className="governance-review"><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Facilitator reasoning (optional)"/><button className="secondary small" onClick={()=>review(p,o.id,false,note)}>Does not meet test</button><button className="primary small" onClick={()=>review(p,o.id,true,note)}>Valid objection</button></div>:o.status==="candidate"?<small>Waiting for facilitator.</small>:o.facilitatorNote&&<small>{o.facilitatorNote}</small>}</div>}
function Integration({p,proposer,integrate}:{p:GovernanceProposal;proposer:boolean;integrate:(id:string,text:string,note:string)=>void}){const [text,setText]=useState(p.proposal),[note,setNote]=useState("");return <div className="governance-round"><span className="section-kicker">5 · Integration</span><h4>Amend the proposal to resolve the objection</h4>{proposer?<div className="governance-inline-form"><textarea rows={5} value={text} onChange={e=>setText(e.target.value)}/><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="How was the objection integrated?"/><button className="primary small" disabled={!text.trim()||!note.trim()} onClick={()=>integrate(p.id,text,note)}>Return to Objection Round</button></div>:<p>Waiting for {personName(p.proposerId)}.</p>}</div>}
function Participation({ids,complete}:{ids:string[];complete:(id:string)=>boolean}){return <div className="round-participation"><strong>Round responses</strong><div>{ids.map(id=><span key={id} className={complete(id)?"complete":"waiting"}>{complete(id)?"✓":"○"} {personName(id)}</span>)}</div></div>}
function MethodGuide({facilitatorId}:{facilitatorId?:string}){return <section className="section governance-method"><div className="section-head"><div><span className="section-kicker">Method reference</span><h2>What each governance step does</h2></div></div><div className="soft-list">{GOVERNANCE_STEPS.map((s,i)=><div className="soft-row" key={s.id}><div><strong>{i+1}. {s.name}</strong><small>{s.description}</small></div></div>)}</div><div className="objection-guide"><span className="section-kicker">Objection test</span><h3>When does a concern count as an objection?</h3><p>The objector needs a reasonable argument that <strong>all four</strong> tests are true.</p><ol className="objection-tests">{OBJECTION_TESTS.map((t,i)=><li key={t}><span>{i+1}</span><p>{t}</p></li>)}</ol><div className="objection-rule"><strong>Who tests it?</strong><p>{facilitatorId?`${personName(facilitatorId)} currently fills Process Steward and acts as facilitator in this prototype.`:"No Process Steward is currently assigned."} The facilitator tests the logic of the objection, not whether they personally agree.</p></div><p className="governance-source-note">This prototype uses the Holacracy v5 objection test as a working method reference. It does not silently make the full Holacracy Constitution binding on SDBP.</p></div></section>}
