"use client";
import { useState } from "react";
import type { RoleDefinition } from "@/lib/domain";
import type { WorkspacePerson } from "@/lib/supabase/workspace";
export function RoleEditorModal({role,people,existing,onClose,onSave,onDelete}:{role:RoleDefinition;people:WorkspacePerson[];existing:boolean;onClose:()=>void;onSave:(r:RoleDefinition)=>Promise<void>;onDelete:(id:string)=>Promise<void>}){
 const[draft,setDraft]=useState(role); const[details,setDetails]=useState(Boolean(role.purpose||role.scope||role.responsibilities.length||role.accountabilities.length));
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className="role-editor compact-modal"><div className="editor-head"><div><span className="section-kicker">Role</span><h2>{existing?`Edit ${role.title}`:"Add role"}</h2></div><button className="quiet editor-close" onClick={onClose}>×</button></div><div className="editor-grid"><label className="field field-wide"><span>Role title</span><input autoFocus value={draft.title} onChange={e=>setDraft({...draft,title:e.target.value})}/></label><label className="field"><span>Type</span><select value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value as RoleDefinition["category"],source:e.target.value==="board"?"SDBP Statutes / applicable law":"SDBP governance"})}><option value="board">Board role</option><option value="operating">Operating role</option></select></label><label className="field"><span>Holder</span><select value={draft.holderIds[0]??""} onChange={e=>setDraft({...draft,holderIds:e.target.value?[e.target.value]:[]})}><option value="">Unfilled</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><button className="quiet role-details-toggle" onClick={()=>setDetails(v=>!v)}>{details?"Hide details":"Add details (optional)"}</button>{details&&<div className="editor-grid role-extra"><label className="field field-wide"><span>Purpose</span><textarea rows={2} value={draft.purpose} onChange={e=>setDraft({...draft,purpose:e.target.value})}/></label><label className="field field-wide"><span>Scope</span><textarea rows={2} value={draft.scope} onChange={e=>setDraft({...draft,scope:e.target.value})}/></label><label className="field"><span>Responsibilities</span><textarea rows={4} value={draft.responsibilities.join("\n")} onChange={e=>setDraft({...draft,responsibilities:lines(e.target.value)})}/></label><label className="field"><span>Accountabilities</span><textarea rows={4} value={draft.accountabilities.join("\n")} onChange={e=>setDraft({...draft,accountabilities:lines(e.target.value)})}/></label></div>}<div className="editor-actions">{existing?<button className="danger" onClick={()=>void onDelete(role.id)}>Remove role</button>:<div/>}<div className="editor-actions-right"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!draft.title.trim()} onClick={()=>void onSave({...draft,title:draft.title.trim(),status:draft.purpose||draft.scope||draft.responsibilities.length||draft.accountabilities.length?"defined":"draft"})}>Save role</button></div></div></section></div>
}
export function blankRole(holderId:string):RoleDefinition{return{id:crypto.randomUUID(),title:"",category:"operating",holderIds:holderId?[holderId]:[],purpose:"",scope:"",responsibilities:[],accountabilities:[],source:"SDBP governance",status:"draft"}}
function lines(v:string){return v.split("\n").map(x=>x.trim()).filter(Boolean)}
