"use client";

import { useEffect, useState } from "react";
import type { Tension } from "@/lib/domain";

export function TensionAvailabilityPoll({ tension, currentUserId, personName, onCreate, onVote, onChoose }: { tension: Tension; currentUserId: string; personName: (id: string) => string; onCreate: (tensionId: string, optionTimes: string[]) => Promise<boolean>; onVote: (pollId: string, availableOptionIds: string[]) => Promise<boolean>; onChoose: (pollId: string, optionId: string) => Promise<boolean> }) {
  const poll = tension.poll;
  const mine = tension.raiserId === currentUserId;
  const [editing, setEditing] = useState(false);
  const [times, setTimes] = useState(["", "", ""]);
  const [available, setAvailable] = useState<string[]>([]);
  useEffect(() => { if (poll) setAvailable(poll.options.filter((option) => option.votes.some((vote) => vote.personId === currentUserId && vote.available)).map((option) => option.id)); }, [poll, currentUserId]);
  if (tension.status !== "needs_sync") return null;
  async function saveTimes() { const optionTimes = times.filter(Boolean).map((value) => new Date(value).toISOString()); if (optionTimes.length >= 2 && await onCreate(tension.id, optionTimes)) setEditing(false); }
  if (!poll) return mine ? <div className="availability-poll-shell compact-poll-shell">{!editing ? <button className="secondary small" onClick={() => setEditing(true)}>Find a time</button> : <PollTimeEditor times={times} setTimes={setTimes} onCancel={() => setEditing(false)} onSave={saveTimes} />}</div> : null;
  const participant = poll.participantIds.includes(currentUserId);
  const chosen = poll.chosenOptionId ? poll.options.find((option) => option.id === poll.chosenOptionId) : undefined;
  const responded = poll.options.some((option) => option.votes.some((vote) => vote.personId === currentUserId));
  return <div className="availability-poll-shell"><div className="availability-poll-head"><div><span className="kind">Find a time</span><h4>{chosen ? "Time chosen" : "When can everyone meet?"}</h4><p>{poll.participantIds.map(personName).join(", ")}</p></div>{mine && !editing && <button className="quiet small" onClick={() => setEditing(true)}>Change options</button>}</div>{chosen && <div className="chosen-time"><strong>{formatPollTime(chosen.startsAt)}</strong><span>Arrange the actual call however is easiest.</span></div>}{!chosen && <div className="poll-options">{poll.options.map((option) => { const yes = option.votes.filter((vote) => vote.available); const checked = available.includes(option.id); return <div className="poll-option" key={option.id}><label className={participant ? "poll-time-choice" : "poll-time-choice read-only"}>{participant && <input type="checkbox" checked={checked} onChange={(event) => setAvailable((items) => event.target.checked ? [...new Set([...items, option.id])] : items.filter((id) => id !== option.id))} />}<span><strong>{formatPollTime(option.startsAt)}</strong><small>{yes.length} available · {option.votes.length}/{poll.participantIds.length} responded{yes.length ? ` · ${yes.map((vote) => personName(vote.personId)).join(", ")}` : ""}</small></span></label>{mine && <button className="secondary small" onClick={() => void onChoose(poll.id, option.id)}>Choose</button>}</div>; })}</div>}{!chosen && participant && <div className="poll-actions"><span>{responded ? "Your availability is recorded." : "Check every time that works for you."}</span><button className="primary small" onClick={() => void onVote(poll.id, available)}>Save availability</button></div>}{editing && mine && <PollTimeEditor times={times} setTimes={setTimes} onCancel={() => setEditing(false)} onSave={saveTimes} warning="Changing the options clears the existing responses." />}</div>;
}

function PollTimeEditor({ times, setTimes, onCancel, onSave, warning }: { times: string[]; setTimes: (times: string[]) => void; onCancel: () => void; onSave: () => void; warning?: string }) { return <div className="poll-time-editor"><div><strong>Propose a few times</strong><p>People simply check the times that work. No calendar integration is created.</p>{warning && <small className="poll-warning">{warning}</small>}</div><div className="poll-time-inputs">{times.map((value, index) => <div className="poll-time-input" key={index}><input type="datetime-local" value={value} onChange={(event) => setTimes(times.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} />{times.length > 2 && <button className="quiet" type="button" onClick={() => setTimes(times.filter((_, itemIndex) => itemIndex !== index))}>×</button>}</div>)}</div><div className="poll-editor-actions">{times.length < 6 && <button className="quiet small" type="button" onClick={() => setTimes([...times, ""])}>+ Add time</button>}<div><button className="quiet small" type="button" onClick={onCancel}>Cancel</button><button className="primary small" type="button" disabled={times.filter(Boolean).length < 2} onClick={onSave}>Create poll</button></div></div></div>; }
function formatPollTime(value: string) { return new Intl.DateTimeFormat("en-GB", { weekday: "short", day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" }).format(new Date(value)); }
