"use client";
import { useState } from "react";
import type { Tension } from "@/lib/domain";
import type { WorkspaceData, WorkspacePerson } from "@/lib/supabase/workspace";
import { TensionAvailabilityPoll } from "@/components/tension-availability-poll";
type Need = "input" | "sync";
export function TensionsWorkspaceView(p:{workspace:WorkspaceData;currentUserId:string;personName:(id:string)=>string;onRaise:(title:string)=>Promise<boolean>;onMarkResolved:(t:Tension)=>Promise<void>;onKeepOpen:(t:Tension)=>Promise<void>;onNeed:(t:Tension,k:Need,ids:string[],detail:string)=>Promise<boolean>;onMoveGovernance:(t:Tension)=>Promise<void>;onResolve:(t:Tension,note:string)=>Promise<void>;onCreatePoll:(id:string,times:string[])=>Promise<boolean>;onVotePoll:(id:string,options:string[])=>Promise<boolean>;onChoosePoll:(id:string,option:string)=>Promise<boolean>}){
 const [draft,setDraft]=useState(""); const [processing,setProcessing]=useState<string|null>(null); const active=p.workspace.tensions.filter(t=>t.status!=="resolved");
 return <><div className="tension-composer"><div className="composer-copy"><span className="section-kicker">Raise a tension</span><h2>What could be better?</h2><p>You do not need to know the solution yet.</p></div><div className="composer-input"><textarea rows={3} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Something is unclear, blocked or could work better…"/><button className="primary" disabled={!draft.trim()} onClick={async()=>{if(await p.onRaise(draft))setDraft("")}}>Raise tension</button></div></div><section className="section"><div className="section-head"><div><span className="section-kicker">Open</span><h2>Tensions that still exist</h2></div><span className="counter">{active.length}</span></div><div className="tension-stream">{active.map(t=><TensionCard key={t.id} tension={t} processing={processing} setProcessing={setProcessing} {...p}/>)}</div></section></>;
}
function TensionCard(p:any){const t:Tension=p.tension;const mine=t.raiserId===p.currentUserId;const processable=t.status==="open"||t.status==="needs_sync";const hasNeed=Boolean(t.latestNote);return <article className="tension-card"><div className="tension-line"/><div className="tension-content"><div className="tension-meta"><span>Raised by {p.personName(t.raiserId)}</span><span>{label(t.status)}</span></div><h3>{t.title}</h3>{t.latestNote&&<p>{t.latestNote}</p>}{t.status==="needs_sync"&&<TensionAvailabilityPoll tension={t} currentUserId={p.currentUserId} personName={p.personName} onCreate={p.onCreatePoll} onVote={p.onVotePoll} onChoose={p.onChoosePoll}/>} {t.status==="awaiting_confirmation"&&mine&&<div className="tension-process-panel"><span className="kind">Resolution check</span><h4>{p.personName(t.resolutionProposedBy??"")} believes this is resolved. Is it resolved for you?</h4><div className="process-actions"><button className="secondary" onClick={()=>void p.onKeepOpen(t)}>No, keep open</button><button className="primary" onClick={()=>void p.onResolve(t,`${p.personName(p.currentUserId)} confirmed the tension is resolved.`)}>Yes, resolved</button></div></div>}{p.processing===t.id&&mine&&processable&&<Process tension={t} people={p.workspace.people} currentUserId={p.currentUserId} onClose={()=>p.setProcessing(null)} onNeed={p.onNeed} onMoveGovernance={p.onMoveGovernance}/>} {mine&&processable&&hasNeed&&p.processing!==t.id&&<div className="tension-resolution-check"><span className="kind">Check the real situation</span><h4>Did you get what you need?</h4><p>If yes, close the tension. If not, adjust what would help.</p><div className="process-actions"><button className="secondary" onClick={()=>p.setProcessing(t.id)}>Not yet · adjust</button><button className="primary" onClick={()=>void p.onResolve(t,`${p.personName(p.currentUserId)} got what was needed and resolved the tension.`)}>Yes, resolved</button></div></div>}</div>{p.processing!==t.id&&processable&&!hasNeed&&<div className="actions compact-actions">{mine&&<button className="secondary" onClick={()=>p.setProcessing(t.id)}>What do you need? →</button>}<button className="quiet" onClick={()=>void p.onMarkResolved(t)}>Resolve</button></div>}{p.processing!==t.id&&processable&&hasNeed&&!mine&&<div className="actions compact-actions"><button className="quiet" onClick={()=>void p.onMarkResolved(t)}>Looks resolved</button></div>}</article>}
function Process({tension,people,currentUserId,onClose,onNeed,onMoveGovernance}:{tension:Tension;people:WorkspacePerson[];currentUserId:string;onClose:()=>void;onNeed:(t:Tension,k:Need,ids:string[],d:string)=>Promise<boolean>;onMoveGovernance:(t:Tension)=>Promise<void>}){const[choice,setChoice]=useState<Need|"governance"|null>(tension.status==="needs_sync"?"sync":null);const[ids,setIds]=useState<string[]>([]);const[detail,setDetail]=useState("");const available=people.filter(x=>x.id!==currentUserId);async function save(k:Need){if(ids.length&&await onNeed(tension,k,ids,detail))onClose()}return <div className="tension-process-panel"><span className="kind">Process tension</span><h4>What do you need now?</h4><div className="outcome-grid compact-outcomes">{[["input","Input or help"],["governance","Change how we work"],["sync","Real conversation"]].map(([id,x])=><button key={id} className={choice===id?"outcome-option selected":"outcome-option"} onClick={()=>setChoice(id as any)}><strong>{x}</strong></button>)}</div>{(choice==="input"||choice==="sync")&&<div className="outcome-form"><p>{choice==="sync"?"Choose who should be involved. After saving, you can optionally add a simple availability poll.":"Choose the people who may help, then reach out in whatever way is quickest."}</p><Picker people={available} selected={ids} setSelected={setIds}/><label className="field"><span>{choice==="sync"?"What needs to be worked through?":"What do you need?"} <em>optional</em></span><textarea rows={3} value={detail} onChange={e=>setDetail(e.target.value)}/></label><button className="primary small" disabled={!ids.length} onClick={()=>void save(choice)}>Keep {choice==="sync"?"conversation":"this"} visible</button></div>}{choice==="governance"&&<div className="outcome-form"><p>Use this when an ongoing role, responsibility, authority or standing way of working should change.</p><button className="primary small" onClick={()=>void onMoveGovernance(tension)}>Move to Governance</button></div>}<div className="process-actions"><button className="quiet" onClick={onClose}>Close</button></div></div>}
function Picker({people,selected,setSelected}:{people:WorkspacePerson[];selected:string[];setSelected:(x:string[])=>void}){return <div className="field"><span>Who do you need?</span><div className="people-picker">{people.map(person=><label key={person.id}><input type="checkbox" checked={selected.includes(person.id)} onChange={e=>setSelected(e.target.checked?[...new Set([...selected,person.id])]:selected.filter(id=>id!==person.id))}/>{person.name}</label>)}</div></div>}
function label(s:Tension["status"]){return s==="awaiting_confirmation"?"awaiting confirmation":s==="needs_sync"?"needs conversation":s}
